# ccmd N — 밤샘 청크: ccmd L 완주 + 통합 + CP4 자료 확정

- **발행**: 2026-10-01 · 엘 → CC
- **대상**: `C:\dev\EDIM`
- **입력**: `lmd-M2-cp4-close-20261001.md` · `cp4-facts-20261001.md` · **CC 가 이미 보유한 ccmd L 원본**
- **한 줄**: **PR #4 머지 → 완료 정의 SSOT → ccmd L 완주(미착수 4쪽 닫기) → 통합·전수검증 → CP4 자료 확정**
- **성격**: 밤샘 batch. 각 STEP 자가검증 통과 시 다음 STEP.

---

## §0. 판정과 전제

### 0.1 lmd M-2 판정 (엘) — 전부 인정

**EBIT 은 (가) 설계대로가 맞다.** CC 설명을 숫자로 따라간 결과 네 군데가 정확히 떨어졌다.

```
세로합      11,929,434 + 2,214,797 + 136,287 + 562,184 = 14,842,702
EBIT        17,035,887 − 14,842,702 = 2,193,185
원가 구성    13,827,830 + 1,659,340 = 15,487,170
Overhead    13,827,830 × 12% = 1,659,340
PCR 간접비   14,842,702 − 13,827,830 = 1,014,872
차이        1,659,340 − 1,014,872 = 644,468   ← 엘이 짚은 값과 동일
```

**산식을 고치지 않은 판단이 옳다.** 원가 기준을 Overhead 포함으로 바꿔 넣어 단언이 False 가 되는 것을 먼저 확인한 것도 옳은 순서다.

교차검증 PASS 4건: 단위 347(=346+1) · 개발 e2e 384(=383+1) · **킷 e2e 381 = 384 − host-only 3** · 볼륨 diff 1건.

### 0.2 엘 결함 3건 (자인 · 이 문서에서 정정)

| 결함 | 정정 |
|---|---|
| host-only 를 2개로 적음 | **3개**다 — S76d(CAD 규칙서 교체) · S79d(호스트 DB bench:seed) · S80c(요율표 파일) |
| "DEMO 견적 숫자를 찾아 고쳐라" | 실제 문제는 숫자가 아니라 **문장**("견적 = 원가 그대로, 한 원도 다를 수 없다")이었다. CC 가 더 정확히 잡았다 |
| `findstr` 검증 명령에 쉼표 포함 | `findstr` 는 쉼표를 구분자로 읽는다. **한 단어씩 따로** 찾는다 |

### 0.3 "완료 정의 4항목" 원문 — 엘이 제공 (STEP 2 에서 커밋)

CC 가 지어내지 않고 "원문 미확보"로 적은 것은 옳은 처리다. 원문은 아래이며, **출처는 2026-09-28 회장님 승인 합의본**(저장소에는 없었고 엘 기록에만 있었다).

```
1. 청사진 51쪽 전부 화면에서 돌고 e2e 로 증명한다.
   외부 자료가 없는 쪽은 '실동(샘플)' 로 따로 센다.
2. 화이트보드 5구역 + ※③ 이 한 흐름으로 이어진다 — 연결 장부의 '없음' 0.
3. 공개 저장소에서 README 를 보고 → CI 가 초록 → docker 한 줄로 실행된다.
4. 회사 실자료는 파일 교체만으로 반영된다(코드 수정 없이).
```

현재 충족: 1번 = 실동 42(샘플 3) · 부분 5 · 미착수 4 → **미충족(진행 중)** / 2번 **충족** / 3번 **충족** / 4번 **충족**.

### 0.4 회장님 결정 (2026-10-01)

| 안건 | 결정 |
|---|---|
| PR #4 | **머지 승인** |
| 밤샘 범위 | **L 완주 + 통합 + CP4 자료 확정** |
| 진행 보고서 | 사장님 보고용 A4 PDF — **엘이 별도 작성** (CC 몫 아님) |

### 0.5 자율 범위

- STEP 0 ~ 7 연속 진행.
- **STEP 1 PR #4 머지는 조건부 승인** — CI 통과 + 충돌 없음일 때만.
- **STEP 5 이후의 L 통합 머지는 회장님 승인 대기** — PR 생성까지가 CC 몫.
- 신규 스키마 마이그레이션이 필요해지면 **그 항목만 멈추고** 설계 문서로 남긴 뒤 나머지 진행(Tier B).
- 되돌릴 수 없는 작업(볼륨 삭제·force push·visibility 변경)은 이 청크에 없다. 필요해지면 중단·보고.

---

## STEP 0 — 실측 + ccmd L 원본 확인

### [작업]

```
cd /d C:\dev\EDIM
git worktree list
git fetch --all --prune
git log --oneline origin/main -1
git status
gh pr list --state open
gh pr checks 4
gh pr view 4 --json mergeable,mergeStateStatus,state
```

L worktree 상태를 본다. 위 `git worktree list` 출력에서 브랜치가 `fix/l-b-tidy` 인 줄의 경로를 복사해 아래 대문자 **LPATH** 자리에 붙여 넣는다.

```
git -C LPATH status --short
git -C LPATH log --oneline -3
```

**ccmd L 원본 문서를 찾는다.** 이 밤샘의 작업 지시가 거기에 있다.

```
dir /s /b ccmd-L*.md
dir /s /b docs\03-handoff
```

찾지 못하면 Downloads 폴더와 이전 세션 첨부도 확인한다.

### [자가검증]

- **성공조건**
  - `origin/main` 이 기록(`ce73119`) 이상
  - PR #4 가 OPEN · MERGEABLE · CI 통과
  - L worktree 의 미커밋 변경 3파일 확인
  - **ccmd L 원본을 찾았다**
- **실패 시 진단**
  - **ccmd L 원본을 못 찾음 → 즉시 중단·보고.** LA·LB·LC 의 구체 지시 없이 추측으로 p42~44·p69 를 구현하지 않는다. 엘이 재발행한다
  - PR #4 가 이미 머지됨 → STEP 1 건너뛰고 기록만
  - L 이 이미 커밋·push 됨 → 그 상태를 기준으로 STEP 4 진행, 차이를 보고
  - main 이 기록과 다름 → 실측을 채택하고 보고

### [체크포인트] PASS → STEP 1 / ccmd L 원본 부재 → 중단·보고

---

## STEP 1 — PR #4 머지 (회장님 승인 2026-10-01)

### [작업]

머지 전에 CI 와 충돌 상태를 다시 본다.

```
gh pr checks 4
gh pr view 4 --json mergeable,mergeStateStatus
```

둘 다 통과면 fast-forward 머지한다. **강제 push 금지.**

```
git fetch origin
git log --oneline origin/main -1
```

머지 후 main 에서 짧은 확인만 한다(전수 검증은 STEP 5).

```
pnpm typecheck
```

### [자가검증]

- **성공조건**: PR #4 가 MERGED · main 이 그 헤드 · typecheck 통과.
- **실패 시 진단**: ff 불가 → 그 사이 main 이 움직였다. 머지하지 말고 중단·보고. CI 실패 → 로그 원문 회수, Auto-fix 켜지 않는다.

### [체크포인트] PASS → STEP 2

---

## STEP 2 — 완료 정의 4항목을 저장소 SSOT 로

> 같은 질문이 또 나오지 않게 저장소에 박는다.

### [작업]

1. 결정 장부(`docs/04-decisions/` 아래)에 §0.3 의 **4항목 원문을 그대로** 적는다. 출처를 함께 적는다 — `2026-09-28 회장님 승인 합의본 · 엘 기록에서 회수`.

2. 각 항목에 **현재 충족 여부와 근거**를 한 줄씩 단다.

```
1번  미충족(진행 중)  실동 42(샘플 3) · 부분 5 · 미착수 4 — 이번 청크로 미착수를 닫는다
2번  충족            연결 장부 이어짐 14 · 약함 0 · 없음 0
3번  충족            README 3단계 · CI verify 통과 · docker 킷 e2e 381/381
4번  충족            카탈로그 파일 교체 → 원가 15,487,170 → 17,866,050 → 복귀
```

3. `cp4-facts-20261001.md` 의 "원문 미확보" 표기를 이 원문으로 교체하고, 어디서 회수했는지 남긴다.

4. README 또는 CP4 사실 묶음에서 이 장부를 참조하게 한다.

### [자가검증]

- **성공조건**: 4항목 원문이 저장소에 있고, 충족 여부가 실측 근거와 함께 붙어 있다. "원문 미확보" 표기가 사라졌다.
- **실패 시 진단**: 충족 여부를 기억으로 쓰고 있으면 멈추고 해당 명령을 다시 돌린다.

### [체크포인트] PASS → STEP 3

---

## STEP 3 — PCR 표에 두 기준을 나란히 (작은 건)

> **근거**: PCR 간접비 1,014,872 가 스냅샷 Overhead 1,659,340 보다 작다. 즉 PCR 표는 원가를 낮게 잡아 이익을 높게 보인다. 기준 한 줄로 설명은 되지만, 사장님은 두 숫자를 나란히 보셔야 오해가 없다.

### [작업]

1. PCR 표 하단(기준 한 줄 옆 또는 아래)에 **참고 줄**을 하나 더 둔다.

```
스냅샷 원가 기준 이익 = 견적 − 스냅샷 원가 = 1,548,717
```

2. 이 값도 **하드코딩하지 않는다** — 견적 총액과 스냅샷 원가에서 계산한다.

3. 인쇄본과 Excel 내보내기 양쪽에 나오게 한다(기준 한 줄과 같은 취급).

4. e2e 단언을 하나 더 둔다: **참고 줄의 값 = 견적 − 스냅샷 원가**.

### [자가검증]

- **성공조건**: 화면·인쇄본·Excel 세 곳에 참고 줄이 보이고 값이 1,548,717 이다. 원가 ₩15,487,170 과 견적 ₩17,035,887 은 **불변**.
- **실패 시 진단**: 두 고정값이 움직였으면 되돌린다.
- **검증 명령**: `python scripts\demo_e2e.py` 의 S80 계열

### [체크포인트] PASS → STEP 4

---

## STEP 4 — ccmd L 완주 (이 밤샘의 본체)

> **작업 지시의 원본은 STEP 0 에서 찾은 ccmd L 문서다.** 이 절은 그 실행 조건만 정한다.
> 성공하면 **미착수 4쪽(p42 · p43 · p44 · p69)이 0 이 된다.**

### [작업]

1. **먼저 L 의 미커밋 변경 3파일을 커밋한다.** 잃어버리지 않게 이것부터 한다.

```
git -C LPATH add -A
git -C LPATH status --short
```

커밋 메시지는 L 의 작업 내용(LB-1 S69 시험 강화 · LB-2 CADRULE 글자 겹침)을 그대로 적는다.

2. **ccmd L 원본을 처음부터 다시 읽고**, 그 STEP 순서대로 LA · LB · LC 를 끝낸다.

```
LA   p42 · p43 · p44 · p69   (확장 단계 — 미착수 4쪽)
LB   툴바 '설계 심볼' 연결   (p58 의 일부)
LC   CI 배선 · DEPLOY 주석
```

3. **LC 에 `--check` 를 함께 넣는다.** 엘 판정: `ci.yml` 이 LC 범위이므로 여기서 배선한다. 이미지 없이 도는 검사라 한 줄이면 된다.

4. 쪽을 닫을 때마다:
   - 화면에서 실제로 도는 경로를 만든다. **문서만 고치는 것은 닫은 것이 아니다**
   - e2e 단계를 추가한다. 캡처가 필요하면 캡처 블록은 **맨 뒤**에 둔다
   - 외부 실자료가 없어 샘플로 닫았으면 **화면에 '샘플' 표지**를 단다(D-4). 판정은 `실동(샘플)`
   - 연결 장부를 갱신한다

5. **스키마 변경이 필요해지면 그 쪽만 멈춘다.** 설계 문서로 남기고 나머지 쪽을 계속 진행한다. 새 마이그레이션을 임의로 만들지 않는다.

6. e2e 에 **고정 대기(sleep)를 넣지 않는다** — 상태 대기로.

### [자가검증]

- **성공조건**
  - ccmd L 의 LA · LB · LC 가 그 문서의 완료 조건대로 닫혔다
  - p42 · p43 · p44 · p69 가 화면에서 돌고 e2e 단계가 붙었다
  - p58 의 툴바 '설계 심볼' 연결이 실동한다
  - `ci.yml` 에 `--check` 가 배선됐다
  - e2e 단계 수가 늘었고 **기존 단계가 하나도 깨지지 않았다**
- **실패 시 진단**
  - 기존 e2e 가 깨짐 → 회귀다. 새 기능을 빼지 말고 **원인을 고친다**
  - 판정을 `실동`으로 올리고 싶은데 화면 경로가 없다 → 올리지 말고 `부분`으로 남기고 이유를 적는다
  - 확장 단계(p42~44·p69)가 기존 흐름과 충돌 → 중단·보고. 기존 흐름이 우선이다
- **검증 명령**: 쪽마다 `pnpm typecheck` + 해당 영역 테스트 + `python scripts\demo_e2e.py`

### [체크포인트] PASS → STEP 5 / 스키마 필요 → 그 쪽만 빼고 진행 + 보고 / 회귀 원인 불명 → 중단·보고

---

## STEP 5 — 통합 · 전수 재검증

### [작업]

1. L 브랜치를 현재 main 위로 rebase 한다. **겹칠 면은 이미 실측돼 있다.**

```
scripts/demo_e2e.py             L: S69          M: S10b · S28c · S80~S82(+S80d)
apps/web/app/lib/output/dxf.ts  L: 글자 배치    M: datumMm(…, sec.dir) 두 줄
  cadEntities
```

**풀이**: `datumMm` 방향 인자를 유지한다. 상세는 `docs/03-handoff/m-to-L-rebase-20260930.md`.

2. rebase 후 전수 재검증(reset 직후). 한글 출력 깨짐 방지 설정을 먼저 한다.

```
chcp 65001
set PYTHONIOENCODING=utf-8
set PYTHONUTF8=1
pnpm install
pnpm db:generate
pnpm db:migrate
pnpm db:reset:demo
pnpm typecheck
pnpm -r test
python scripts\demo_e2e.py
```

DB 검증은 `package.json` 의 `:test` 목록 **전 종목**을 돌린다.

```
findstr /C:":test" package.json
```

3. **docker 킷 e2e 도 1회** 돌린다. host-only 3단계(S76d · S79d · S80c)는 SKIP 줄을 남기고 건너뛴다.

```
docker compose -p edim-prod-n -f docker-compose.prod.yml config
docker compose -p edim-prod-n -f docker-compose.prod.yml up -d --build
docker compose -p edim-prod-n -f docker-compose.prod.yml ps
```

끝나면 정리하고, 이번에 만든 볼륨만 이름을 정확히 지정해 지운다. **와일드카드·`prune` 금지.**

```
docker compose -p edim-prod-n -f docker-compose.prod.yml down
docker volume ls
```

4. 브랜치를 push 하고 PR 을 올린다. **머지하지 않는다.**

### [자가검증]

- **성공조건**: rebase 충돌이 위 두 면에서만 났고 풀이대로 해결됨 · 개발 e2e 전 단계 통과(384 이상) · 킷 e2e 종료코드 0(통과 수 = 개발 수 − 3) · DB 검증 전 종목 PASS · main 미변경 · PR 생성.
- **실패 시 진단**
  - 예상 밖의 파일에서 충돌 → 중단·보고. 그 파일이 무엇인지 먼저 적는다
  - 킷에서만 실패 → **빌드 산출물에 빠진 파일**을 먼저 의심한다(09-29 규칙 파일 사고와 같은 부류)
  - host-only 가 3개보다 많아짐 → 목록을 적어 회수한다
- **검증 명령**: 각 명령의 마지막 요약 줄 **원문**. 요약 금지.

### [체크포인트] PASS → STEP 6

---

## STEP 6 — 판정 갱신 · 확정판 6

### [작업]

1. 판정 데이터에 L 이 닫은 쪽을 반영하고 생성기를 돌린다.

```
python docs\02-reports\build_blueprint_match.py
```

2. `--check` 로 page-map 과 판정 데이터 일치를 확인한다.

3. 기대 판정: **미착수 4 → 0**. 닫힌 쪽이 `실동` 인지 `실동(샘플)` 인지 각각 명시하고, 합이 51 + 개념·표지 19 = 70 인지 확인한다.

4. 연결 장부를 갱신한다. `없음` 이 0 을 유지하는지 확인한다.

5. 각 쪽의 `judge`(판정자)·`why`(근거) 칸을 채운다. 이번에 닫은 쪽은 **`CC 초안 — 엘 재측정 전`** 으로 표시한다. 최종 판정은 엘이 한다.

### [자가검증]

- **성공조건**: `--check` EXIT 0 · 합 70 · 미착수 0 · 연결 장부 `없음` 0.
- **실패 시 진단**: 수가 안 맞으면 **생성기를 고치지 말고** 어느 쪽 데이터가 틀렸는지 먼저 적는다. 보고서에 맞추려고 데이터를 고치는 것은 방향이 반대다.

### [체크포인트] PASS → STEP 7

---

## STEP 7 — CP4 사실 묶음 최종 + lmd

### [작업]

1. `cp4-facts-20261001.md` 를 현행화한다(파일명은 그대로 두고 내용 갱신).

```
- main 커밋 · 이번 청크 PR 번호(머지 대기)
- 최종 검증 수치 전부: typecheck · 단위 · DB 종목별 · 개발 e2e · 킷 e2e
- 판정 수와 실동(샘플) 목록 · 근거
- 부분 5쪽 각각: 막는 것 한 줄 · 누구 몫
- 완료 정의 4항목 원문 + 충족 여부 + 근거   ← STEP 2 결과
- 바뀐 불변식(견적 = 원가 × (1 + 마진율))
- host-only e2e 3단계 목록
- 샘플로 남은 것: 단가 · CAD 규칙서 · PCR 요율표 · 마진율 · KAD 슬롯 대응표
```

2. `lmd-N-L-finish-20261001.md` 를 쓴다.

```
## 1. 한 일 — STEP 0~7 각 한 줄
## 2. STEP 0 실측 (ccmd L 원본을 어디서 찾았는지 포함)
## 3. ccmd L 완주 결과 — LA · LB · LC 각각 무엇을 어떻게 닫았는지
##    닫은 쪽마다: 화면 경로 · e2e 단계 · 실동/실동(샘플) 구분 · 샘플 표지 유무
## 4. 실측 수치 원문 — typecheck / 단위 / DB 전 종목 / 개발 e2e / 킷 e2e(SKIP 줄 포함)
## 5. rebase 결과 — 충돌 면과 풀이 · 예상 밖 충돌 유무
## 6. 판정 — 확정판 6 수치 · --check 결과 · 연결 장부
## 7. 닫지 못한 것 — 쪽 · 막는 것 · 누구 몫
## 8. 엘에게 묻는 것 (선택지로)
## 9. 내가 한 판정은 '주장'이다
```

3. `features\*.sinc` 가 있으면 판정 출력 전문을 회신한다. 없으면 건너뛴다.

---

## 머지 승인 게이트 (L 통합분 — 회장님 승인 대상)

- [ ] 개발 e2e 전 단계 통과 (384 이상, 수치 원문)
- [ ] 킷 e2e 종료코드 0 · SKIP 3단계 출력에 명시
- [ ] DB 검증 전 종목 PASS
- [ ] 판정 미착수 0 · 합 70 · `--check` EXIT 0
- [ ] 연결 장부 `없음` 0
- [ ] 원가 ₩15,487,170 · 견적 ₩17,035,887 불변
- [ ] main 미변경 (PR 로만)
- [ ] rebase 충돌이 예상 두 면에서만 발생

---

## 회장님 직접 확인 (H-5)

```
cd /d C:\dev\EDIM
git fetch
git pull
pnpm install
pnpm db:generate
pnpm db:migrate
pnpm db:reset:demo
pnpm build
pnpm --filter @edim/web start
```

시연은 운영 모드로 한다(DEMO.md 0-A). 개발 모드 `pnpm dev` 는 예비.

**정상이면**
- 원가 ₩15,487,170 · 견적 ₩17,035,887
- 견적 인쇄본 PCR 세부표에 **원가 기준 한 줄** + **스냅샷 원가 기준 이익 1,548,717 참고 줄**
- 툴바 '설계 심볼' 이 눌리고 반응함
- p42 · p43 · p44 · p69 에 해당하는 화면이 실제로 뜸

**실패 신호**
- 원가가 ₩15,487,170 이 아님 → 되돌려야 함
- 참고 줄 값이 1,548,717 이 아님
- 툴바 심볼이 눌려도 아무 일 없음 → LB 미완

**실패하면** — F12 Console·Network 캡처 + 터미널 마지막 30줄.

---

## 하지 말 것

- **ccmd L 원본 없이 추측으로 p42~44·p69 구현** (없으면 중단·보고)
- L 의 미커밋 변경을 커밋하지 않은 채 rebase (잃어버린다)
- 원가 ₩15,487,170 · 견적 ₩17,035,887 바꾸기
- 화면 경로 없이 판정을 `실동` 으로 올리기
- 보고서 수치에 맞추려고 판정 데이터 고치기
- host-only 단계를 **조용히** 건너뛰기 (SKIP 줄 필수)
- 신규 스키마 마이그레이션 (Tier B — 그 쪽만 멈추고 설계만)
- L 통합분 main 직접 머지 (회장님 승인 대상)
- 볼륨을 `prune` 이나 와일드카드로 지우기
- CI 실패 시 Auto-fix 켜기
- `git push --force`
- 명령 블록 안에 `#` 로 주석 달기
- `findstr` 에 쉼표 넣기 (구분자로 읽혀 0건이 된다 — 한 단어씩)
- e2e 에 고정 대기 넣기
- 회장님 승인 없는 패키지 설치

---

## 이 청크 이후

| 순서 | 항목 | 누구 |
|---|---|---|
| 1 | lmd N 회수 → 엘 판정 | 엘 |
| 2 | L 통합분 PR 머지 승인 | 회장님 |
| 3 | **CP4 보고** (최종 판정) | 엘 |
| 4 | 부분 5쪽 — p9 클라우드 · p21 자료 원천 · p23 실도면 · p38 부품 CAD·편집기 · p58 Free CAD | 회장님 · 사장님 · CAD 담당 |
| 5 | 실 단가 · 회사 표 · 마진 정책 · RCCS 문법 · KAD 슬롯 · D1 Special · AI 키 | 회장님 · 사장님 |

---

*엘 → CC · ccmd N · 2026-10-01 · 기대값은 lmd 교차검증 기준 · 엘 저장소 실측 아님 · 실측이 이긴다*
