#!/usr/bin/env python3
"""EDIM 20→80 완성 시나리오·설계안 생성기. usage: build_plan.py out.html [light]"""
import sys, os, html
OUT=sys.argv[1]; THEME=sys.argv[2] if len(sys.argv)>2 else "dark"
D=os.path.dirname(os.path.abspath(__file__)); DECK=os.path.join(D,"..","deck")
css=open(os.path.join(DECK,"deck.css"),encoding="utf-8").read()
if THEME=="light": css+=open(os.path.join(DECK,"deck_light.css"),encoding="utf-8").read()
css+="""
.tbl{width:100%;border-collapse:collapse;font-size:1.12cqw;line-height:1.45}.tbl th{text-align:left;color:var(--mut);font-weight:600;font-size:1cqw;padding:.5cqw .7cqw;border-bottom:.12cqw solid var(--line)}
.tbl td{padding:.62cqw .7cqw;border-bottom:.08cqw solid var(--line);vertical-align:top}.tbl td b{color:var(--teal)}.tbl .k{font-family:'JetBrains Mono',monospace;color:var(--amber);white-space:nowrap;font-size:1cqw}
.bars{flex:1;display:flex;flex-direction:column;justify-content:center;gap:1.25cqw}.bar{display:grid;grid-template-columns:17cqw 1fr 9cqw;gap:1.2cqw;align-items:center;font-size:1.25cqw}
.bar .nm b{display:block;font-size:1.35cqw}.bar .nm span{color:var(--mut);font-size:.98cqw}.track{height:1.7cqw;background:var(--panel);border:.1cqw solid var(--line);border-radius:.9cqw;position:relative;overflow:hidden}
.now{position:absolute;left:0;top:0;bottom:0;background:var(--teal);border-radius:.9cqw}.tgt{position:absolute;left:0;top:0;bottom:0;border-right:.3cqw solid var(--amber);background:repeating-linear-gradient(135deg,transparent 0 .5cqw,rgba(224,169,62,.22) .5cqw 1cqw)}
.val{font-family:'JetBrains Mono',monospace;font-size:1.15cqw}.val i{font-style:normal;color:var(--amber)}
.note{font-size:1.05cqw;color:var(--mut);line-height:1.5}
.cols{flex:1;min-height:0;display:grid;grid-template-columns:1fr 1fr;gap:1.4cqw}.card{background:var(--panel);border:.1cqw solid var(--line);border-radius:.9cqw;padding:1.2cqw 1.4cqw;display:flex;flex-direction:column;gap:.55cqw;min-height:0}
.card h3{font-size:1.5cqw;display:flex;gap:.7cqw;align-items:baseline}.card h3 em{font-style:normal;font-family:'JetBrains Mono',monospace;color:var(--teal);font-size:1.1cqw}.card h3 small{margin-left:auto;font-size:.95cqw;color:var(--amber);font-weight:600}
.card ul{margin:0;padding-left:1.2cqw;font-size:1.06cqw;line-height:1.5}.card .dod{font-size:1cqw;color:var(--mut);border-top:.08cqw dashed var(--line);padding-top:.45cqw;margin-top:auto}.card .dod b{color:var(--teal)}
.scn{flex:1;display:grid;grid-template-columns:repeat(3,1fr);gap:1cqw;align-content:center}.sc{background:var(--panel);border:.1cqw solid var(--line);border-radius:.8cqw;padding:1cqw 1.2cqw}.sc b{font-size:1.25cqw}.sc i{font-style:normal;font-family:'JetBrains Mono',monospace;color:var(--teal);font-size:1cqw;margin-right:.5cqw}.sc p{font-size:1.02cqw;color:var(--mut);margin-top:.35cqw;line-height:1.45}.sc.new{border-color:var(--amber)}.sc.new i{color:var(--amber)}
svg text{font-family:'Pretendard','Malgun Gothic','Noto Sans CJK KR',sans-serif}
"""
def S(no,title,body,foot): return f'<section class="slide"><div class="stage"><header><span class="no">{no}</span><h2>{title}</h2></header>{body}<footer>{foot}</footer></div></section>'
ZONES=[("※⑤ MainForm","5영역·승인·RLS 실동 / 캔버스 명령은 라벨",70,90),("※② EDIM Toolbox","Macro 실행 고리 실동 / 플로팅 창·자연어·역번역 없음",45,85),
("CPQ · BOM 산출","1줄기 실동 / BOM이 슬롯→함수, 단가 샘플",40,85),("※① PLM Set-Up","등록 화면 0 (코드·관계·Key Dimension)",5,75),
("※④ ERP","프로젝트·승인 DB만 / 구매·공정 0",15,60),("※③ 관리자 영역","설계 확정 · 구현 0 (Special 슬롯·DB①/②·학습 AI)",0,70)]
bars="".join(f'<div class="bar"><div class="nm"><b>{n}</b><span>{d}</span></div><div class="track"><div class="tgt" style="width:{t}%"></div><div class="now" style="width:{c}%"></div></div><div class="val">{c} → <i>{t}</i></div></div>' for n,d,c,t in ZONES)
now=round(sum(z[2] for z in ZONES)/6); tgt=round(sum(z[3] for z in ZONES)/6)
P=[]
P.append(f'<section class="slide title"><div class="stage"><div class="kick">EDIM · 완성 시나리오 & 설계안</div><h1>20 → <em>80</em></h1><p class="sub">등뼈 한 줄기에서, 화이트보드 다섯 구역이 모두 움직이는 발표까지. 확정 장부(2026-09-19) 위에서 짠 순서·설계·검증 기준입니다.</p><div class="meta">점검 초안 v0.1 · 2026-09-19 · main 6bfa8e6 기준</div></div></section>')
P.append(S("01","지금 어디인가 — 구역별 시연 가능 깊이",f'<div class="bars">{bars}</div><div class="note">채움 = 현재 · 빗금 끝 = 목표. 단순 평균 {now} → {tgt}. <b>점수는 엘 제안 기준</b>(0=없음 · 50=한 흐름이 화면에서 끝까지 · 100=청사진 전 기능)이며 공수 가중은 하지 않았습니다. 회장님 조정 대상.</div>',"“깊이는 이미 증명했습니다. 이제 남은 다섯 구역에 한 줄기씩 꽂습니다.”"))
P.append(S("02","‘80’의 정의 — 발표에서 보여줄 아홉 장면",'<div class="scn">'+"".join(f'<div class="sc {c}"><b><i>{i}</i>{t}</b><p>{p}</p></div>' for i,t,p,c in [
("1","Set-Up — 코드를 등록한다","Sub Code · Product Code · Relationship을 화면에서 등록 (p31–34)","new"),("2","선택 — 코드 조립","A~F 슬롯 → EU-55-2123-630SS · Rev A/B",""),("3","Toolbox — 말로 규칙을 만든다","플로팅 창에서 자연어 → Macro → Flowchart·Description 역번역 → 승인 (p27·p57)","new"),
("4","EDIM Run","승인된 식만 결정론 실행 · 런타임 LLM 0",""),("5","BOM — 관계에서 뽑힌다","BomCodeRun이 Code Relationship을 따라 하위 코드 추출 → 스냅샷 (p62)","new"),("6","산출 — 도면·원가·문서","치수 하나 바꾸면 전파되는 DXF · 단가표 기반 Cost · Quotation 1종 (p65–66)","new"),
("7","경계 — Special Tool Box","Macro로 안 되는 계산을 우리가 만든 모듈이 메인폼에 UI로 제공 · 별도 과금 지점","new"),("8","관리자 — DB① → DB②","같은 원천에서 두 DB로 프로젝션 · 유사도 실측 표시 · 역류 차단","new"),("9","ERP로 넘긴다","BOM → 구매 요청 목록 1흐름 (p51–52)","new")])+'</div><div class="note">주황 테두리 = 새로 만드는 장면 7개. 나머지 2개는 이미 실동.</div>',"“다섯 구역 모두에서 ‘화면에서 끝까지 도는 한 흐름’ — 이것이 80의 기준입니다.”"))
flow='''<svg viewBox="0 0 1600 560" style="flex:1;min-height:0;width:100%"><defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0 L10,5 L0,10 z" fill="#2fbfa6"/></marker><marker id="b" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0 L10,5 L0,10 z" fill="#e0a93e"/></marker></defs>
<path d="M150,300 C260,300 250,150 380,150" fill="none" stroke="#2fbfa6" stroke-width="5" marker-end="url(#a)"/><path d="M610,150 C720,150 700,300 830,300" fill="none" stroke="#2fbfa6" stroke-width="5" marker-end="url(#a)"/>
<path d="M150,330 C300,420 300,440 380,440" fill="none" stroke="#2fbfa6" stroke-width="5" marker-end="url(#a)"/><path d="M610,440 C720,440 720,340 830,330" fill="none" stroke="#2fbfa6" stroke-width="5" marker-end="url(#a)"/>
<path d="M1060,315 C1130,315 1130,315 1190,315" fill="none" stroke="#2fbfa6" stroke-width="5" marker-end="url(#a)"/><path d="M1420,315 C1470,315 1470,315 1500,315" fill="none" stroke="#2fbfa6" stroke-width="5" marker-end="url(#a)"/>
<path d="M495,205 C495,290 495,320 495,385" fill="none" stroke="#e0a93e" stroke-width="3" stroke-dasharray="9 7" marker-end="url(#b)"/>
<g font-weight="700">
<g><rect x="20" y="255" width="130" height="100" rx="18" fill="#0e7c6b"/><text x="85" y="298" text-anchor="middle" fill="#eafff9" font-size="20">P0</text><text x="85" y="326" text-anchor="middle" fill="#eafff9" font-size="15">발표 안전망</text></g>
<g><rect x="380" y="95" width="230" height="110" rx="18" fill="#111926" stroke="#2fbfa6" stroke-width="3"/><text x="495" y="138" text-anchor="middle" fill="#2fbfa6" font-size="20">P1 · 코드 기반 등뼈</text><text x="495" y="166" text-anchor="middle" fill="#EAF1FA" font-size="15" font-weight="500">Set-Up 등록 + BomCodeRun</text><text x="495" y="188" text-anchor="middle" fill="#8fa3bf" font-size="13" font-weight="500">※① · CPQ/BOM</text></g>
<g><rect x="380" y="385" width="230" height="110" rx="18" fill="#111926" stroke="#2fbfa6" stroke-width="3"/><text x="495" y="428" text-anchor="middle" fill="#2fbfa6" font-size="20">P2 · 청사진대로 Toolbox</text><text x="495" y="456" text-anchor="middle" fill="#EAF1FA" font-size="15" font-weight="500">플로팅 창 · 자연어 · 역번역 · Table</text><text x="495" y="478" text-anchor="middle" fill="#8fa3bf" font-size="13" font-weight="500">※② · ※⑤</text></g>
<g><rect x="830" y="255" width="230" height="120" rx="18" fill="#111926" stroke="#e0a93e" stroke-width="3"/><text x="945" y="298" text-anchor="middle" fill="#e0a93e" font-size="20">P3 · 경계를 보이게</text><text x="945" y="326" text-anchor="middle" fill="#EAF1FA" font-size="15" font-weight="500">플랫폼 관리자 · Special 슬롯</text><text x="945" y="348" text-anchor="middle" fill="#EAF1FA" font-size="15" font-weight="500">DB①→DB② · 학습 1수준</text><text x="945" y="368" text-anchor="middle" fill="#8fa3bf" font-size="13" font-weight="500">※③</text></g>
<g><rect x="1190" y="260" width="230" height="110" rx="18" fill="#111926" stroke="#2fbfa6" stroke-width="3"/><text x="1305" y="303" text-anchor="middle" fill="#2fbfa6" font-size="20">P4 · 산출의 폭</text><text x="1305" y="331" text-anchor="middle" fill="#EAF1FA" font-size="15" font-weight="500">치수 전파 도면 · 견적 · 구매</text><text x="1305" y="353" text-anchor="middle" fill="#8fa3bf" font-size="13" font-weight="500">CPQ · ※④</text></g>
<g><rect x="1500" y="265" width="90" height="100" rx="18" fill="#e0a93e"/><text x="1545" y="308" text-anchor="middle" fill="#1a1204" font-size="20">P5</text><text x="1545" y="334" text-anchor="middle" fill="#1a1204" font-size="14">발표</text></g></g>
<text x="265" y="120" fill="#8fa3bf" font-size="14">P1·P2는 병행 가능</text><text x="510" y="300" fill="#e0a93e" font-size="14">Table 관리가 BOM 단가·표를 공급</text>
<text x="830" y="420" fill="#8fa3bf" font-size="14">P3는 P1의 관계 테이블(정렬화된 DB)과</text><text x="830" y="442" fill="#8fa3bf" font-size="14">P2의 승인 Registry 위에 선다</text></svg>'''
P.append(S("03","순서 — 무엇이 무엇 위에 서는가",flow,"“정렬된 코드 DB가 먼저, 그 위에 도구, 그 위에 경계. 회장님이 말씀하신 ‘바닥 = 정렬화’ 순서 그대로입니다.”"))
def card(tag,t,size,items,dod): return f'<div class="card"><h3><em>{tag}</em>{t}<small>{size}</small></h3><ul>'+"".join(f"<li>{i}</li>" for i in items)+f'</ul><div class="dod"><b>DoD</b> {dod}</div></div>'
P.append(S("04","설계 ① — 등뼈와 도구",'<div class="cols">'+
card("P1","코드 기반 등뼈 (※① + BOM)","L · Tier B(스키마)",["테이블 3개: <b>sub_code · product_code · code_relationship</b> (RCCS 카탈로그 층, 테넌트 RLS) + <b>bom_code_run</b> 스냅샷(PLM 인스턴스 층) — GAP1 확정안","등록 화면 최소 3종(p31·33·34): 틀은 우리가, 수치·관계는 사용자가 입력","BomCodeRun: Main Code에서 관계를 재귀 CTE로 따라 하위 코드 추출 → 스냅샷 저장(개정 연동)","현재 슬롯→함수 규칙을 <b>관계 시드로 이관</b>, 기존 buildBom은 회귀 기준으로 보존","단가: p67 4테이블 중 구매단가 1종부터 — 회사 표가 오면 값만 교체"],"같은 코드 → 기존 11행과 동일 BOM(회귀 테스트) · 관계 1줄 수정 시 BOM이 따라 바뀜 · RLS 격리 테스트")+
card("P2","청사진대로 Toolbox (※②)","L · Tier A 위주",["<b>플로팅 창</b>(UI Tool / Program Tool 탭 · 드래그 · 도킹 · 중앙 안 가림) — 2026-07-14 확정 요구","자연어 → Macro: <b>이미 있는 compile 엔진</b>을 화면에 연결(build-time 1회, 실패 시 재시도, 키 없으면 Scripted 폴백)","5형식 맞물림(p57): Macro → Flowchart · Description <b>역번역</b>(결정론 디컴파일, STEP 5)","Table 관리 · Data Up-Load(p60): 샘플 상수 Table1/NS를 DB 테이블로 — 승인 거쳐야 실행에 반영","캔버스 명령 9개 중 Arrangement · Move · Add 3개 실동"],"자연어 1문장 → 승인 → Run 값 일치 · 역번역 결과가 원식과 의미 동치(골든 테스트) · 표 값 수정 → 승인 전엔 Run 불변")+'</div>',"“새 엔진을 만드는 게 아니라, 이미 만든 결정론 코어를 청사진의 자리에 꽂는 일입니다.”"))
P.append(S("05","설계 ② — 경계와 산출",'<div class="cols">'+
card("P3","경계를 보이게 (※③)","L · Tier B",["<b>플랫폼 관리자</b> 역할 + 콘솔: 3계층(플랫폼 → 회사 관리자 → 하부) 완성, “System DB 영향 = Platform 승인”(p44·54) 시연","<b>Special Tool Box 슬롯</b>: 우리가 만든 계산 모듈을 등록 → 메인폼에 UI로 노출 → 사용 기록(과금 근거). 첫 사례 1개는 회장님 지정","<b>DB① / DB②</b>: 스키마 분리 + π_user 프로젝션 작업 → 구조 유사도 실측 수치 표시 · DB②→DB① 쓰기 권한 자체를 없앰","학습 AI 1수준(p23): 도면·문서 메타데이터 추출 → DB① 적재. build-time 전용, 런타임 LLM 0 유지"],"사용자 역할로 Special 모듈 수정 시도 → 차단 · 프로젝션 후 유사도 수치 재현 · DB② 역할의 DB① INSERT 실패 테스트")+
card("P4","산출의 폭 (CPQ · ※④)","M · Tier A/B",["<b>마스터 1장 + 치수 전파</b>: Key Dimension 셋업(p38–40) 최소판 → 치수 1개 변경 → DXF 재생성(평면 + 승인도 1장)","문서 1종: Quotation / PCR(p66) — Cost 카드 값과 동일 수치, 인쇄용 PDF","Tech Data 1종(p15–16): 매크로 결과값 표","ERP 1흐름(p51–52): BOM 스냅샷 → 구매 요청 목록(엑셀 Export)","Drawings.status(작성중/검토/승인/발행) + 승인 문서 잠금"],"치수 변경 전후 DXF를 ezdxf로 파싱해 해당 엔티티만 달라짐 · 견적 합계 = Cost API 값 · 발행 상태 문서 수정 차단")+'</div>',"“Special 첫 사례와 DB 분리는 방향을 정하는 결정이라, 착수 전에 회장님 확인을 받겠습니다.”"))
P.append(S("06","P0·P5와 결정 요청",'<div class="cols"><div class="card"><h3><em>P0 · P5</em>발표 안전망과 패키지</h3><table class="tbl"><tr><th>항목</th><th>상태</th></tr><tr><td>리허설 잔재 리셋 · e2e 14단계</td><td><b>완료</b> (main)</td></tr><tr><td>덱 v0.4 · 확정 장부 repo 이중화</td><td><b>완료</b> (main 6bfa8e6)</td></tr><tr><td>회장님 Windows 로컬 실행</td><td class="k">0회 — PC 필요</td></tr><tr><td>회사 실 표(단가 · Table1/NS)</td><td class="k">자료 대기</td></tr><tr><td>로컬 88md 코퍼스 백업</td><td class="k">PC 필요</td></tr><tr><td>P5: Phase마다 e2e 장면 추가 → 덱 v1.0(5구역 지도) → 리허설</td><td>각 Phase 끝에 누적</td></tr></table></div><div class="card"><h3><em>결정</em>회장님께 여쭐 것</h3><table class="tbl"><tr><th>#</th><th>질문</th></tr><tr><td class="k">D1</td><td>Special Tool Box <b>첫 시연 사례</b> — 어떤 계산으로 할지 (Macro로 안 되는 것의 대표)</td></tr><tr><td class="k">D2</td><td>‘80’ 기준 — 구역별 목표치·가중을 이대로 둘지</td></tr><tr><td class="k">D3</td><td>P1·P2 병행 여부 (엘 단독 트랙이면 P1 → P2 순차 권장)</td></tr><tr><td class="k">D4</td><td>학습 AI 1수준의 입력 — 도면(DXF) 먼저인지 기술문서 먼저인지</td></tr><tr><td class="k">D5</td><td>발표 시점 — 없으면 P1 완료 시점에 중간 시연 권장</td></tr></table><div class="dod"><b>규모(엘 추정)</b> P1 3~4 · P2 3~4 · P3 4~5 · P4 2~3 · P5 1~2 세션. 근거: M1~M3가 각 1세션 내외였던 실적. 회사 자료·PC 작업은 제외.</div></div></div>',"“순서와 기준은 초안입니다. 결정은 회장님 몫이고, 저는 그 위에서 끝까지 만들겠습니다.”"))
js="addEventListener('keydown',e=>{const s=[...document.querySelectorAll('.slide')];const i=Math.round(scrollY/innerHeight);if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();s[Math.min(i+1,s.length-1)].scrollIntoView()}if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();s[Math.max(i-1,0)].scrollIntoView()}})"
open(OUT,"w",encoding="utf-8").write(f'<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EDIM 20→80 완성 시나리오·설계안</title><style>{css}</style></head><body>{"".join(P)}<script>{js}</script></body></html>')
print("pages",len(P),"avg",now,"->",tgt)
